//Author: Cosmos Bennett

import java.util.ArrayList;

import java.util.Scanner;

public class RunNeuralNetwork
{
    //attribs
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    
    //constructor
    public static void main ( String [] programInputs )
    {
        doNeuralNetworkTraining ( );
        renderMainMenu ( );
    }
    
    
    //methods
    public static void renderMainMenu ( )
    {
        System.out.println ( "=====================" );
        System.out.println ( "======Neural Network Practice 2026 January" );
        System.out.println ( "1. Get neural network guess for XORGATE input [1,1] : " );
        System.out.println ( "2. Get neural network guess for XORGATE input [0,1] : " );
        System.out.println ( "3. Get neural network guess for XORGATE input [1,0] : " );
        System.out.println ( "4. Get neural network guess for XORGATE input [0,0] : " );
        System.out.println ( "5. Get me out of here" );
        
        int userOption = new Scanner ( System.in ).nextInt ( );
        
        switch ( userOption )
        {
            case 1: 
                neuralNetwork.doForwardPropagation ( new int [ ] { 1, 1 } );
                
                System.out.println ( "Neural network guess for [1,1] = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            break;
            
            case 2: 
                neuralNetwork.doForwardPropagation ( new int [ ] { 0, 1 } );
                
                System.out.println ( "Neural network guess for [0,1] = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            break;
            
            case 3: 
                neuralNetwork.doForwardPropagation ( new int [ ] { 1, 0 } );
                
                System.out.println ( "Neural network guess for [1,0] = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            break;
            
            case 4: 
                neuralNetwork.doForwardPropagation ( new int [ ] { 0, 0 } );
                
                System.out.println ( "Neural network guess for [0,0] = " + neuralNetwork.getOutcome ( ) );
                returnToMainMenu ( );
            break;    
            
            case 5: 
                System.exit ( 0 );
            break;  
        }
    }
    
    public static void doNeuralNetworkTraining ( )
    {
        System.out.println ( ">>> training model  " );
        for ( int tDI = 0; tDI < getTrainingData ( ).size ( ); tDI ++ )
        {
            System.out.print ( "." );
            String inputLineRaw = getTrainingData ( ).get ( tDI );
            String inputLine = inputLineRaw.split ( ":" ) [ 0 ];
            
            int inputs [ ] = { Integer.parseInt ( inputLine.split ( "," ) [ 0 ] ), Integer.parseInt ( inputLine.split ( "," ) [ 1 ] ) };
            
            //System.out.println ( ">>> inputLine > " + inputLine );
            //System.out.println ( ">>> inputs [ 0 ] > " + Integer.parseInt ( inputLine.split ( "," ) [ 0 ]  ) );
            //System.out.println ( ">>> inputs [ 1 ] > " + Integer.parseInt ( inputLine.split ( "," ) [ 1 ]  ) );
            
            neuralNetwork.doForwardPropagation ( inputs );
            
            //System.out.println ( ">>> propagated " );
            
            int target = Integer.parseInt ( inputLineRaw.split ( ":" ) [ 1 ] );
            neuralNetwork.doBackwardPropagation ( target );
        }
        System.out.println ( ">>> training complete !  " );
    }
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );

        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,0:0" );
        
        return returnValue;
    }
    
    public static void returnToMainMenu ( ) 
    {
        new Scanner ( System.in ).nextLine ( );
        System.out.println ( "\f" );
        renderMainMenu ( );
    }
}